<a href="https://colab.research.google.com/github/Sukantanath108/Data-Science-and-ML-journey/blob/main/iris_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install mglearn
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import mglearn

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 581.4/581.4 kB 23.3 MB/s eta 0:00:00


In [29]:
from sklearn.datasets import load_iris
iris_database = load_iris()
print("keys of iris_database : \n {}".format(iris_database.keys()))


keys of iris_database : 
 dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])
       0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]


In [22]:
print(iris_database['DESCR'][:193] + "\n ...")
print(iris_database['target'][:110]) #prints 110 out of 150 examples
print(iris_database['feature_names'][:])
print(type(iris_database))

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, pre
 ...
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2]
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]


In [21]:
print("Target names are : {}".format(iris_database["target_names"]))
print(iris_database["target_names"])  # both prints the same
print("the shape of the whole dataset is :",iris_database['data'].shape)

Target names are : ['setosa' 'versicolor' 'virginica']
the shape of the whole dataset is : (150, 4)


In [35]:
print("the first five elements are : \n" , iris_database['data'][:5])
print(type(iris_database['data']))
print("target are: {}".format(iris_database['target'].shape))
print(iris_database['target'].shape) # same things again

print("target are: \n {} ".format(iris_database['target']))

the first five elements are : 
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
<class 'numpy.ndarray'>
target are: (150,)
(150,)
target are: 
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2] 


In [37]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(iris_database['data'],iris_database['target'],random_state = 0) # normally we used X,y instead of iris_database['data']
print(X_train.shape)
print(y_test.shape)
# this is a 75-25 split by default and randomly selected so that we get all the classes of the problem (in this case 0,1,2)

(112, 4)
(38,)


In [53]:
# pdf = pd.DataFrame(X_train,columns = iris_database.feature_names)

# create a scatter matrix from dataframe , color by y_train
# grr = pd.scatter_matrix(pdf, c = y_train , figsize = (15,15), marker = "x" , hist_kwds = {"bins" : 20} , s = 60 , aplha = 0.8 , cmap = mglearn.cm3)

In [40]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 1)
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=1)

In [41]:
y_pred = knn.predict(X_test)
print("Test set predictions : \n {}".format(y_pred))

Test set predictions : 
 [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


In [47]:
knn.score(X_test,y_test)
print("the test score is : {:.4f}".format(np.mean(y_pred == y_test)))

the test score is : 0.9737


In [51]:
X_new = [[2.3 , 6 , 7.1 , 4.2]]
pred = knn.predict(X_new)
print("the target feature is : {}".format(pred))
print("Name of the target is {}".format(iris_database["target_names"][pred]))

the target feature is : [2]
Name of the target is ['virginica']


In [52]:
X_new_1 = [[3 , 1.6 , 2.1 , 1.2]]
pred_1 = knn.predict(X_new_1)
print("the target feature is : {}".format(pred_1))
print("Name of the target is {}".format(iris_database["target_names"][pred_1]))

the target feature is : [0]
Name of the target is ['setosa']
